export function GridModeLogo(): JSX.Element {
  return (
    <div
      className="gridmode-logo"
      aria-label="GridMode"
    >
      <svg
        viewBox="0 0 320 320"
        role="img"
      >
        <defs>
          <linearGradient
            id="gridmodeLogoStroke"
            x1="56"
            y1="44"
            x2="260"
            y2="276"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#f8f4e9" />
            <stop
              offset="0.52"
              stopColor="#9ed1b7"
            />
            <stop
              offset="1"
              stopColor="#e3b55c"
            />
          </linearGradient>
          <linearGradient
            id="gridmodeLogoTile"
            x1="70"
            y1="58"
            x2="248"
            y2="252"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#33392f" />
            <stop
              offset="1"
              stopColor="#171914"
            />
          </linearGradient>
        </defs>
        <rect
          x="36"
          y="36"
          width="248"
          height="248"
          rx="44"
          fill="#151512"
        />
        <rect
          x="48"
          y="48"
          width="224"
          height="224"
          rx="36"
          fill="url(#gridmodeLogoTile)"
          stroke="url(#gridmodeLogoStroke)"
          strokeWidth="10"
        />
        <path
          d="M112 79v162M160 79v162M208 79v162M79 112h162M79 160h162M79 208h162"
          fill="none"
          stroke="#f8f4e9"
          strokeLinecap="round"
          strokeWidth="13"
          opacity="0.92"
        />
        <rect
          x="87"
          y="87"
          width="50"
          height="50"
          rx="9"
          fill="#9ed1b7"
        />
        <rect
          x="137"
          y="137"
          width="46"
          height="46"
          rx="8"
          fill="#f8f4e9"
        />
        <rect
          x="183"
          y="183"
          width="50"
          height="50"
          rx="9"
          fill="#e3b55c"
        />
      </svg>
      <span>GridMode</span>
    </div>
  );
}
